<?php

namespace AppBundle\Entity\Repository;

/**
 * SensorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SensorRepository extends \Doctrine\ORM\EntityRepository
{
    public function createFindAllQuery()
    {
        return $this->_em->createQuery(
            "
            SELECT s
            FROM AppBundle:Sensor s
            "
        );
    }
    public function createFindOneByIdQuery(int $id)
    {
        $query = $this->_em->createQuery(
            "
            SELECT s
            FROM AppBundle:Sensor s
            WHERE s.id = :id
            "
        );
        $query->setParameter('id', $id);
        return $query;
    }
    public function deleteQuery($id)
    {
        $query = $this->_em->createQuery(
            "
            DELETE 
            FROM AppBundle:Sensor s
            WHERE s.id = :id
            "
        );
        $query->setParameter('id', $id);
        return $query;
    }
}
